(function(){
'use strict';
const KEY='fluffy_planet_v2',SCHEMA=3,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clamp=n=>Math.max(0,Math.min(100,n));
const {PETS,petSVG}=window.FluffyPets,{ITEMS,FOODS,TOYS,ACHIEVEMENTS}=window.FluffyItems,{pick,phase}=window.FluffyDialogue;
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const dayDiff=(a,b)=>Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/864e5);
const base=()=>({schema:SCHEMA,adopted:false,petId:'corgi',name:'团团',coins:120,love:12,xp:0,hunger:84,thirst:82,fun:80,clean:90,energy:78,totalInteractions:0,dailyInteractions:0,dailyReward:false,dailyDate:today(),bornAt:Date.now(),lastTick:Date.now(),owned:['none-hat','none-clothes','none-accessory'],outfit:{hat:'none-hat',clothes:'none-clothes',accessory:'none-accessory'},memories:['相遇的第一天'],counts:{},achievements:[],lastCheckin:'',streak:0,maxStreak:0,checkinCycle:0});
function load(){const f=base();try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(!raw||typeof raw!=='object')return f;const s={...f,...raw,schema:SCHEMA,counts:{...f.counts,...(raw.counts||{})},outfit:{...f.outfit,...(raw.outfit||{})}};['coins','love','xp','hunger','thirst','fun','clean','energy','totalInteractions','dailyInteractions','bornAt','lastTick','streak','maxStreak','checkinCycle'].forEach(k=>s[k]=Number.isFinite(Number(s[k]))?Number(s[k]):f[k]);s.petId=PETS.some(p=>p.id===s.petId)?s.petId:f.petId;s.name=typeof s.name==='string'&&s.name.trim()?s.name.trim():f.name;s.owned=[...new Set([...f.owned,...(Array.isArray(s.owned)?s.owned:[]).filter(id=>ITEMS.some(i=>i.id===id))])];for(const c of ['hat','clothes','accessory'])if(!s.owned.includes(s.outfit[c])||!ITEMS.some(i=>i.id===s.outfit[c]&&i.cat===c))s.outfit[c]=f.outfit[c];s.achievements=Array.isArray(s.achievements)?s.achievements.filter(id=>ACHIEVEMENTS.some(a=>a.id===id)):[];return s}catch(e){console.warn('存档损坏，已安全恢复。',e);return f}}
let state=load(),selectedPet=state.petId,shopCat='hat',wardrobeCat='hat',busy=false,achievementQueue=[];
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function pet(){return PETS.find(p=>p.id===state.petId)||PETS[0]}function level(){return Math.floor(state.xp/90)+1}
function decay(){const hrs=Math.min(720,Math.max(0,(Date.now()-(state.lastTick||Date.now()))/36e5));state.hunger=Math.max(5,clamp(state.hunger-hrs*2.3));state.thirst=Math.max(5,clamp(state.thirst-hrs*2.8));state.fun=Math.max(5,clamp(state.fun-hrs*1.7));state.clean=Math.max(5,clamp(state.clean-hrs*1.15));state.energy=Math.max(5,clamp(state.energy-hrs*1.5));state.lastTick=Date.now();if(state.dailyDate!==today()){state.dailyDate=today();state.dailyInteractions=0;state.dailyReward=false}}
function mood(){const low=['hunger','thirst','fun','clean','energy'].sort((a,b)=>state[a]-state[b])[0];if(state[low]<25)return {hunger:'饿扁扁',thirst:'口渴了',fun:'想你陪',clean:'灰扑扑',energy:'困成团'}[low];const avg=(state.hunger+state.thirst+state.fun+state.clean+state.energy)/5;return avg>84?'幸福冒泡':avg>60?'心情很好':'需要关心'}
function timeTheme(){document.querySelector('.game').dataset.time=phase()}
function renderPet(){const art=petSVG(pet(),state.outfit);$('#petArt').innerHTML=art;$('#wardrobePet').innerHTML=art;$('#profilePet').innerHTML=art;const speed=pet().traits.includes('active')?'.65s':pet().traits.includes('sleepy')?'1.9s':pet().traits.includes('gentle')?'1.55s':'1.1s';$('#petArt').querySelectorAll('.tail').forEach(x=>x.style.animationDuration=speed)}
function render(){decay();timeTheme();$('#petName').textContent=state.name;$('#petMood').textContent=`Lv.${level()} · ${mood()}`;$('#coinTop').textContent=Math.floor(state.coins);$('#shopCoins').textContent=Math.floor(state.coins);$('#loveTop').textContent=Math.round(state.love);$('#streakTop').textContent=state.streak;['hunger','thirst','fun','clean','energy'].forEach(k=>{$(`#${k}Bar`).style.width=`${clamp(state[k])}%`;document.querySelector(`[data-need="${k}"]`).classList.toggle('low',state[k]<25)});renderPet();renderItems('#shopItems',shopCat,true);renderItems('#wardrobeItems',wardrobeCat,false);renderAlbum();renderAchievements();renderCheckin();renderProfile();if(!state.adopted)$('#adoptModal').classList.add('show');save()}
function speak(kind='general'){const line=pick(state,kind);$('#speech').textContent=line;return line}function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1400)}
function floats(icon,n=3){const room=$('#room');for(let i=0;i<n;i++)setTimeout(()=>{const e=document.createElement('i');e.className='float';e.textContent=icon;e.style.left=`${35+Math.random()*35}%`;e.style.top=`${48+Math.random()*14}%`;room.appendChild(e);setTimeout(()=>e.remove(),1300)},i*120)}
function count(k){state.counts[k]=(state.counts[k]||0)+1}function traitGain(action,gain){const t=pet().traits;if(t.includes('active')&&['ball','wand','highfive'].includes(action))gain.fun=(gain.fun||0)+4;if(t.includes('foodie')&&action==='feed')gain.love=(gain.love||0)+2;if(t.includes('sleepy')&&action==='sleep')gain.love=(gain.love||0)+2;if(t.includes('cool')&&state.love<35&&['hug','face'].includes(action))gain.love=Math.max(1,(gain.love||0)-2);if(t.includes('timid')&&action==='highfive')gain.fun=Math.max(0,(gain.fun||0)-2);return gain}
function finishAction(ms=950){setTimeout(()=>{busy=false;window.FluffyMotion.resume();render()},ms)}
function interact(action,gain,anim,icon,ms=900){if(busy||!state.adopted)return false;busy=true;window.FluffyMotion.pause();gain=traitGain(action,{...gain});state.totalInteractions++;state.dailyInteractions++;state.xp+=9;count(action);for(const[k,v]of Object.entries(gain))state[k]=clamp((state[k]||0)+v);speak(action);window.FluffyMotion.action(anim,ms);floats(icon);checkAchievements();save();finishAction(ms+80);return true}
function openChoices(type){let list,title,kicker;if(type==='food'){list=FOODS;title='今天吃什么？';kicker='食盆已经准备好'}else{list=TOYS;title='挑一个玩具';kicker='一起玩最开心'}$('#choiceTitle').textContent=title;$('#choiceKicker').textContent=kicker;$('#choiceGrid').innerHTML=list.map(x=>`<button class="choice" data-choice="${x.id}" data-type="${type}"><span>${x.emoji}</span><b>${x.name}</b><small>${type==='food'?`🪙 ${x.cost}`:'开心大幅增加'}</small></button>`).join('');$('#choiceModal').classList.add('show')}
function feed(id){const f=FOODS.find(x=>x.id===id);if(!f||state.coins<f.cost){toast('金币还不够哦～');return}state.coins-=f.cost;$('#choiceModal').classList.remove('show');interact('feed',{hunger:f.hunger,fun:f.fun,love:2},'eat',f.emoji)}
function playToy(id){const t=TOYS.find(x=>x.id===id);if(!t)return;$('#choiceModal').classList.remove('show');interact(id==='wand'?'wand':'ball',{fun:t.fun,energy:t.energy,hunger:-4,love:3},t.anim,t.emoji)}
const ACTIONS={head:()=>interact('head',{love:4,fun:7},'love','💗'),face:()=>interact('face',{love:2,fun:5},'shake','💕'),belly:()=>interact('belly',{love:4,fun:9},'belly','✨'),hug:()=>interact('hug',{love:6,fun:5},'love','🤗'),highfive:()=>interact('highfive',{love:3,fun:9,energy:-3},'highfive','⭐'),chin:()=>interact('chin',{love:4,fun:6},'love','💞'),feed:()=>openChoices('food'),water:()=>interact('water',{thirst:38,energy:3,love:2},'drink','💧'),ball:()=>interact('ball',{fun:24,energy:-10,hunger:-4,love:3},'jump','🎾'),wand:()=>interact('wand',{fun:28,energy:-12,love:3},'spin','🪄'),brush:()=>interact('brush',{clean:10,fun:6,love:3},'brush','✨'),wash:()=>interact('wash',{clean:36,fun:-2,love:2},'wash','🫧'),dry:()=>interact('dry',{clean:8,energy:-2,love:3},'dry','💨'),sleep:()=>{window.FluffyMotion.moveTo(24,48,1000).then(()=>interact('sleep',{energy:42,hunger:-6,thirst:-5,love:2},'sleep','💤',1800))},call:()=>{window.FluffyMotion.moveTo(50,10,750).then(()=>interact('call',{fun:7,love:3},'love','💗'))}};
function renderAdopt(){$('#adoptGrid').innerHTML=PETS.map(p=>`<button class="pet-choice ${selectedPet===p.id?'selected':''}" data-pet="${p.id}"><div class="pet-preview">${petSVG(p)}</div><b>${p.name}</b><small>${p.desc}</small></button>`).join('');$$('.pet-choice').forEach(b=>b.onclick=()=>{selectedPet=b.dataset.pet;renderAdopt()})}
function renderItems(target,cat,shop){const list=ITEMS.filter(i=>i.cat===cat);$(target).innerHTML=list.map(i=>{const owned=state.owned.includes(i.id),selected=state.outfit[cat]===i.id;return `<div class="item ${selected?'selected':''}" data-item="${i.id}"><div class="item-art">${i.emoji}</div><b>${i.name}</b><div class="item-row"><span>${i.price?`🪙 ${i.price}`:'免费'}</span><button ${shop&&owned?'disabled':''}>${shop?(owned?'已拥有':'购买'):(selected?'已穿上':'穿上')}</button></div></div>`}).join('');$$(`${target} .item`).forEach(card=>card.onclick=()=>{const i=ITEMS.find(x=>x.id===card.dataset.item);if(shop){if(state.owned.includes(i.id))return;if(state.coins<i.price)return toast('金币不够啦');state.coins-=i.price;state.owned.push(i.id);count('buy');toast('买到新衣服啦！')}else{if(!state.owned.includes(i.id))return toast('先去商店带它回家吧');state.outfit[i.cat]=i.id;toast('换装完成 ✨')}checkAchievements();save();render()})}
function renderAlbum(){const list=[['🏡','相遇的第一天',`${Math.max(1,Math.floor((Date.now()-state.bornAt)/864e5)+1)} 天前开始陪伴`],['💗',`亲密度 ${Math.round(state.love)}`,'每次互动都会被记住'],['🎾',`互动 ${state.totalInteractions} 次`,'一起玩过的瞬间'],['🎀',`收藏 ${state.owned.length} 件`,'衣橱慢慢变丰富']];$('#albumGrid').innerHTML=list.map(x=>`<div class="memory"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}
function renderAchievements(){$('#achievementGrid').innerHTML=ACHIEVEMENTS.map(a=>`<div class="achievement ${state.achievements.includes(a.id)?'':'locked'}"><span>${a.icon}</span><div><b>${a.name}</b><small>${a.desc}</small></div></div>`).join('')}
function showNextAchievement(){if(!achievementQueue.length)return;const a=achievementQueue.shift();$('#achievementIcon').textContent=a.icon;$('#achievementTitle').textContent=a.name;$('#achievementPopup').classList.add('show');setTimeout(()=>{$('#achievementPopup').classList.remove('show');setTimeout(showNextAchievement,400)},2300)}
function checkAchievements(){const fresh=ACHIEVEMENTS.filter(a=>!state.achievements.includes(a.id)&&a.test(state));if(!fresh.length)return;state.achievements.push(...fresh.map(a=>a.id));achievementQueue.push(...fresh);showNextAchievement()}
function renderCheckin(){const rewards=[20,25,30,35,40,50,100],next=(state.checkinCycle%7);$('#weekGrid').innerHTML=rewards.map((r,i)=>`<div class="day ${i<next?'done':''} ${i===next?'current':''}"><b>Day ${i+1}</b><span>${i===6?'🌙':'🪙'}</span><small>${i===6?'100 + 睡帽':r+' 金币'}</small></div>`).join('');const done=state.lastCheckin===today();$('#checkinBtn').disabled=done;$('#checkinBtn').textContent=done?'今天已签到':'今日签到'}
function checkin(){if(state.lastCheckin===today())return;const diff=state.lastCheckin?dayDiff(state.lastCheckin,today()):1;if(diff===1)state.streak+=1;else state.streak=1;state.maxStreak=Math.max(state.maxStreak,state.streak);const day=state.checkinCycle%7,rewards=[20,25,30,35,40,50,100];state.coins+=rewards[day];state.checkinCycle=(day+1)%7;if(day===6&&!state.owned.includes('nightcap'))state.owned.push('nightcap');state.lastCheckin=today();count('checkin');floats(day===6?'🌙':'🪙',5);toast(day===6?'签到成功！获得 100 金币和星星睡帽':'签到成功，金币到账！');checkAchievements();save();render()}
function renderProfile(){const p=pet();$('#profileName').textContent=state.name;$('#profileLines').innerHTML=`<div><b>品种</b><br>${p.name}</div><div><b>性格</b><br>${p.desc}</div><div><b>等级</b><br>Lv.${level()}</div><div><b>陪伴</b><br>${Math.max(1,Math.floor((Date.now()-state.bornAt)/864e5)+1)} 天</div>`}
function onBehavior(name){const kinds={yawn:'energy','sleep-bed':'energy','play-ball':'ball','run-owner':'call'};speak(kinds[name]||'general');const icons={'play-ball':'🎾','smell-plant':'🌿','sleep-bed':'💤','find':'🔎','happy-jump':'✨'};if(icons[name])floats(icons[name],2)}
$$('[data-body-action]').forEach(b=>b.onclick=e=>{e.stopPropagation();ACTIONS[b.dataset.bodyAction]()});$$('[data-action]').forEach(b=>b.onclick=()=>ACTIONS[b.dataset.action]());
$$('[data-furniture]').forEach(b=>b.onclick=()=>{const f=b.dataset.furniture;if(f==='bed')ACTIONS.sleep();else if(f==='food')openChoices('food');else if(f==='water')ACTIONS.water();else if(f==='toys')openChoices('toy');else if(f==='plant')window.FluffyMotion.forceBehavior('smell-plant');else if(f==='sofa')window.FluffyMotion.forceBehavior('sit');else speak('general')});
$('#choiceGrid').onclick=e=>{const b=e.target.closest('[data-choice]');if(!b)return;b.dataset.type==='food'?feed(b.dataset.choice):playToy(b.dataset.choice)};
$$('.bottom-nav button').forEach(b=>b.onclick=()=>{$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.screen').forEach(x=>x.classList.toggle('active',x.id===b.dataset.screen));b.dataset.screen==='roomScreen'?window.FluffyMotion.resume():window.FluffyMotion.pause();render()});
$$('#shopTabs button').forEach(b=>b.onclick=()=>{shopCat=b.dataset.cat;$$('#shopTabs button').forEach(x=>x.classList.toggle('active',x===b));renderItems('#shopItems',shopCat,true)});$$('#wardrobeTabs button').forEach(b=>b.onclick=()=>{wardrobeCat=b.dataset.cat;$$('#wardrobeTabs button').forEach(x=>x.classList.toggle('active',x===b));renderItems('#wardrobeItems',wardrobeCat,false)});
$$('[data-open]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.open}Modal`).classList.add('show');render()});$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('show'));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=='adoptModal')m.classList.remove('show')});
$('#checkinBtn').onclick=checkin;$('#adoptBtn').onclick=()=>{const p=PETS.find(x=>x.id===selectedPet);state=base();state.adopted=true;state.petId=p.id;state.name=$('#nameInput').value.trim()||p.nick;state.bornAt=Date.now();$('#adoptModal').classList.remove('show');speak('general');checkAchievements();save();render()};$('#resetBtn').onclick=()=>{if(confirm('确定重新领养吗？当前进度会清空。')){localStorage.removeItem(KEY);location.reload()}};
window.FluffyMotion.init({stage:$('#petStage'),canAct:()=>state.adopted&&!busy&&$('#roomScreen').classList.contains('active'),getState:()=>state,onBehavior});
window.FluffyGame={getState:()=>JSON.parse(JSON.stringify(state)),forceBehavior:n=>window.FluffyMotion.forceBehavior(n),checkin,migrate:load,ACTIONS,dialogueCount:window.FluffyDialogue.total,applyTime:h=>document.querySelector('.game').dataset.time=phase(h)};
renderAdopt();render();speak('general');checkAchievements();setInterval(()=>{if(!busy){render();const low=['hunger','thirst','fun','clean','energy'].sort((a,b)=>state[a]-state[b])[0];if(state[low]<25)speak('general')}},60000);
})();
