(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],{PETS,petSVG,getPet}=window.FluffyPets;let speechTimer,idleSpeechCursor=0;
const rasterArt=(p,kind='lineup')=>p.id==='nutuan'?(kind==='lineup'?`<div class="pet-art pixi-pet-host" data-pixi-pet="nutuan" role="img" aria-label="糯团 PixiJS 互动角色"><span class="pixi-loading">正在来到房间…</span></div>`:`<img class="${kind==='profile'?'profile-pet-raster':'mini-pet-raster'}" src="./assets/pets/nuotuan/idle.webp" alt="糯团透明角色素材">`):petSVG(p.id);
function renderHUD(){const s=window.FluffyState.get();$('#level').textContent=s.level;$('#coins').textContent=Math.floor(s.coins);$('#xpBar').style.width=`${s.xp}%`}
function slot(p){const s=window.FluffyState.pet(p.id);return `<article class="pet-slot" data-pet="${p.id}">${rasterArt(p)}<button class="pet-hit special" data-interact="petSpecial" aria-label="摸${p.name}的${p.special}"></button><button class="pet-hit head" data-interact="petHead" aria-label="摸${p.name}的头"></button><button class="pet-hit body" data-interact="petBelly" aria-label="摸${p.name}的肚子"></button><button class="pet-nameplate" data-open-pet="${p.id}"><b>${p.name}</b><span>♥</span><small>Lv. ${p.level}</small><i class="lovebar"><i style="width:${s.love}%"></i></i></button></article>`}
function renderLineup(){$('#petLineup').innerHTML=PETS.map(slot).join('')}
function renderCards(){$('#lifeStrip').innerHTML=PETS.map(p=>`<article class="life-card" style="--scene1:${p.scene[0]};--scene2:${p.scene[1]}"><div class="mini-pet">${rasterArt(p,'card')}</div><div class="card-actions"><button data-card-action="feed" data-pet="${p.id}">🍎<small>喂食</small></button><button data-card-action="play" data-pet="${p.id}">🖐<small>互动</small></button><button data-card-action="clean" data-pet="${p.id}">🧼<small>清洁</small></button><button data-card-action="sleep" data-pet="${p.id}">🌙<small>睡觉</small></button></div></article>`).join('')}
function say(id,text){const petEl=document.querySelector(`.pet-slot[data-pet="${id}"]`),bubble=$('#speech'),room=$('#room');if(!petEl)return;const a=petEl.getBoundingClientRect(),r=room.getBoundingClientRect();bubble.textContent=`${getPet(id).name}：${text}`;bubble.style.left=`${Math.max(76,Math.min(r.width-260,a.left-r.left+a.width*.45))}px`;bubble.style.top=`${Math.max(90,a.top-r.top-35)}px`;bubble.classList.remove('show');void bubble.offsetWidth;bubble.classList.add('show');clearTimeout(speechTimer);speechTimer=setTimeout(()=>bubble.classList.remove('show'),3600)}
function interact(id,action){const s=window.FluffyState.get();if(action==='feed'&&s.coins<8)return toast('金币不够，先完成任务吧');const out=window.FluffyReactions.react(id,action,action);if(out.repeat>=2)discover(id,'习惯');if(window.FluffyState.pet(id).interactions>=5)discover(id,'喜好');renderHUD();const bar=document.querySelector(`.pet-slot[data-pet="${id}"] .lovebar i`);if(bar)bar.style.width=`${out.love}%`;window.FluffyAnimations.play(id,out.animation,1200,action,out);if(id!=='nutuan')say(id,out.text);return out}
function discover(id,item){const s=window.FluffyState.pet(id);if(!s.discoveries.includes(item)){s.discoveries.push(item);window.FluffyState.save();toast(`发现了${getPet(id).name}的新${item}`)}}
function bindDynamic(){$$('#petLineup [data-interact]').forEach(b=>b.onclick=e=>{e.stopPropagation();interact(b.closest('.pet-slot').dataset.pet,b.dataset.interact)});$$('[data-open-pet]').forEach(b=>b.onclick=()=>openPanel('profile',b.dataset.openPet))}
function panel(title,body){$('#panelContent').innerHTML=`<small>绒绒星球</small><h2>${title}</h2>${body}`;$('#panelModal').classList.add('show');$('#panelModal').setAttribute('aria-hidden','false')}
function profile(id){const p=getPet(id),s=window.FluffyState.pet(id),known=s.discoveries,persona=window.FluffyPersonalities.get(p.id);return `<div class="panel-grid"><div class="panel-item">${rasterArt(p,'profile')}</div><div class="panel-item"><b>种族</b><p>${p.species}</p><b>性格</b><p>${p.personality}</p><b>生日</b><p>${p.birthday}</p><b>代表动作</b><p>${persona.representativeAction}</p><b>亲密阶段</b><p>${relationshipName(s.love)} · ${Math.round(s.love)}</p></div><div class="panel-item"><b>喜欢</b><p>${known.includes('喜好')?p.likes.join('、'):'???'}</p><b>讨厌</b><p>${known.includes('习惯')?p.dislikes.join('、'):'???'}</p><b>最爱食物</b><p>${known.includes('喜好')?p.favoriteFoods.join('、'):'???'}</p></div><div class="panel-item"><b>互动次数</b><p>${s.interactions}</p><b>秘密</b><p>${s.love>=80?p.secret:'???'}</p><b>收藏</b><p>${p.id==='maiduo'?'叶子、糖纸、石头':'???'}</p></div></div>`}
function relationshipName(v){return v<20?'陌生':v<40?'熟悉':v<60?'朋友':v<80?'亲近':'最亲密伙伴'}
function openPanel(type,id){const s=window.FluffyState.get();if(type==='profile')return panel(`${getPet(id||'nutuan').name}的档案`,profile(id||'nutuan'));if(type==='pets')return panel('五位伙伴',`<div class="panel-grid">${PETS.map(p=>`<button class="panel-item" data-profile="${p.id}">${rasterArt(p,'card')}<b>${p.name}</b><small>${p.species}</small></button>`).join('')}</div>`),bindProfiles();if(type==='bag')return panel('背包',`<div class="panel-grid">${['🥛 牛奶 ×3','🍪 饼干 ×5','🍑 桃子 ×2','🍃 季节叶片 ×4','🎾 软球 ×1'].map(x=>`<div class="panel-item">${x}</div>`).join('')}</div>`);if(type==='shop')return panel('绒光商店',`<p>金币 ${s.coins}</p><div class="panel-grid">${['软枕头|80','桃木镜|120','玉米粒|30','收藏册|150'].map(x=>{const[n,c]=x.split('|');return`<div class="panel-item shop-item"><b>${n}</b><button data-buy="${c}" data-name="${n}">◉ ${c}</button></div>`}).join('')}</div>`),bindShop();if(type==='mail')return panel('星球来信','<div class="panel-item"><b>欢迎回家</b><p>五位伙伴已经在暖光房间等你啦。</p></div>');if(type==='settings')return panel('设置','<div class="panel-item"><button id="resetSave">重新开始存档</button><p>进度保存在本机浏览器中。</p></div>'),bindReset();panel('家园','<p>暖光正好，五位伙伴都在做自己的事。</p>')}
function bindProfiles(){$$('[data-profile]').forEach(b=>b.onclick=()=>openPanel('profile',b.dataset.profile))}function bindShop(){$$('[data-buy]').forEach(b=>b.onclick=()=>{const cost=+b.dataset.buy;if(window.FluffyState.get().coins<cost)return toast('金币不够');window.FluffyState.addCoins(-cost);toast(`买下了${b.dataset.name}`);renderHUD();openPanel('shop')})}function bindReset(){const b=$('#resetSave');if(b)b.onclick=()=>{if(confirm('确定重新开始吗？现有进度会被清空。')){window.FluffyState.reset();location.reload()}}}
function renderArchive(){$('#archiveGrid').innerHTML=PETS.map(p=>{const persona=window.FluffyPersonalities.get(p.id);return`<article class="archive-card"><div class="portrait">${rasterArt(p,'card')}</div><h2>${p.name}</h2><small>${p.species}</small><dl><dt>性格</dt><dd>${p.personality}</dd><dt>喜欢</dt><dd>${p.likes.join('、')}</dd><dt>讨厌</dt><dd>${p.dislikes.join('、')}</dd><dt>生日</dt><dd>${p.birthday}</dd><dt>代表动作</dt><dd>${persona.representativeAction}</dd><dt>亲密</dt><dd>${relationshipName(window.FluffyState.pet(p.id).love)}</dd></dl><button class="primary" data-archive-pet="${p.id}">查看档案</button></article>`}).join('');$$('[data-archive-pet]').forEach(b=>b.onclick=()=>openPanel('profile',b.dataset.archivePet))}
function renderTasks(){const total=PETS.reduce((n,p)=>n+window.FluffyState.pet(p.id).interactions,0),tasks=[['和任意伙伴互动 3 次',total>=3],['摸摸特别部位',PETS.some(p=>window.FluffyState.pet(p.id).recentPettingArea==='petSpecial')],['发现一项角色喜好',PETS.some(p=>window.FluffyState.pet(p.id).discoveries.includes('喜好'))]];$('#taskList').innerHTML=tasks.map(([t,d])=>`<article class="task ${d?'done':''}"><h2>${d?'✓':'○'} ${t}</h2><p>${d?'已完成':'去家园陪陪它们吧'}</p></article>`).join('')}
function showScreen(id){$$('.home-screen,.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='archiveScreen')renderArchive();if(id==='tasksScreen')renderTasks();id==='homeScreen'?window.FluffyBehaviors.start(idle,relationshipEvent):window.FluffyBehaviors.stop()}
function idle(id,name){const state=window.FluffyState.pet(id);window.FluffyAnimations.play(id,window.FluffyBehaviors.animation(id,name));idleSpeechCursor++;if(idleSpeechCursor%2===0){const line=window.FluffyDialogue.pick(id,{action:'idle',event:name,state:window.FluffyReactions.moodOf(state),relationship:window.FluffyReactions.relationship(state.love)},state.recentDialogueIds);say(id,line.text)}}function relationshipEvent(e){e.pets.forEach((id,i)=>window.FluffyAnimations.play(id,e.animations[i]));say(e.pets[0],e.text)}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1800)}
function init(){renderHUD();renderLineup();renderCards();renderArchive();renderTasks();bindDynamic();window.FluffyPixiReady=window.FluffyPixi.mount({onInteract:action=>interact('nutuan',action),onDialogue:text=>say('nutuan',text)});$$('[data-card-action]').forEach(b=>b.onclick=()=>interact(b.dataset.pet,b.dataset.cardAction));$$('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$$('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$$('[data-back]').forEach(b=>b.onclick=()=>showScreen('homeScreen'));$$('[data-close]').forEach(b=>b.onclick=()=>{$('#panelModal').classList.remove('show');$('#panelModal').setAttribute('aria-hidden','true')});$('#panelModal').onclick=e=>{if(e.target.id==='panelModal')e.target.classList.remove('show')};$('#exploreBtn').onclick=()=>{window.FluffyState.addCoins(25);toast('探索完成：发现季节叶片，金币 +25');renderHUD()};const camera=$('[data-action="camera"]');camera.onclick=()=>{window.FluffyAnimations.play('taoke','groom');say('taoke','先别按——好，现在！')};window.FluffyBehaviors.start(idle,relationshipEvent)}
window.FluffyGame={init,interact,openPanel,showScreen,state:window.FluffyState.get,reaction:window.FluffyReactions.react,dialogueCount:window.FluffyDialogue.total,petIds:PETS.map(p=>p.id),relationshipEvents:window.FluffyRelationships.EVENTS,pixi:()=>window.FluffyPixi.getDebugState()};document.addEventListener('DOMContentLoaded',init);
})();
