(function(){
'use strict';
const registry=new Map(),dialogueCursors=new Map(),recentBehaviors=new Map();
const TIME_ORDER=['morning','day','evening','night'],RELATION_ORDER=['low','familiar','friend','close','partner'];
function chinaTime(){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(part=>[part.type,part.value])),hour=Number(parts.hour);return hour>=6&&hour<10?'morning':hour>=10&&hour<17?'day':hour>=17&&hour<20?'evening':'night'}
function relationship(value){if(typeof value==='string')return value;return value<20?'low':value<40?'familiar':value<60?'friend':value<80?'close':'partner'}
function register(config){if(!config?.id||registry.has(config.id))throw Error(`Invalid or duplicate personality: ${config?.id||'unknown'}`);config.dialogue=config.dialogue||{};config.eventDialogue=config.eventDialogue||{};config.interactionDialogue=config.interactionDialogue||{};registry.set(config.id,Object.freeze(config));return config}
function get(id){return registry.get(id)||registry.get('nutuan')}
function groupFor(context={}){if(context.repeat>=4)return'repeat';if(context.action==='petSpecial')return'petSpecial';if(['petHead','petCheek','petBelly'].includes(context.action))return'petHead';if(context.action==='feed')return'feed';if(context.action==='play')return'play';if(['clean','sleep'].includes(context.action)||['hungry','sleepy'].includes(context.state||context.mood))return'needs';if(context.event)return'idle';if(context.relationship)return'relationship';if(context.action==='idle')return'idle';return context.time?'time':'greeting'}
function contextualPool(config,context,time,relation){const eventName=context.event||context.behavior,event=config.eventDialogue[eventName];if(event)return{group:`event-${eventName}`,lines:Array.isArray(event)?event:[event]};const matches=(config.contextLines||[]).filter(line=>(!context.action||line.actions?.includes(context.action))&&(!line.times||line.times.includes(time))&&(!line.states||line.states.includes(context.state||context.mood))&&(!line.relationships||line.relationships.includes(relation))&&(!line.events||line.events.includes(eventName))&&(!line.actions||line.actions.includes(context.action))&&(!line.trait||(config.traits[line.trait]>=Number(line.min||0)&&config.traits[line.trait]<=Number(line.max??100))));if(matches.length)return{group:'context',lines:matches};const group=groupFor(context),lines=config.dialogue[group]||config.dialogue.greeting||[];return{group,lines}}
function chooseLine(config,context={},recent=[],cursorStore=dialogueCursors){const time=chinaTime(),relation=relationship(context.relationship??context.love??50),{group,lines}=contextualPool(config,context,time,relation);if(!lines.length)return{id:`${config.id}-silent`,text:'……'};const normalized=lines.map((line,index)=>typeof line==='string'?{id:`${group}-${index}`,text:line}:line),recentIds=new Set(recent),fresh=normalized.filter(line=>!recentIds.has(`${config.id}-${line.id}`)),pool=fresh.length?fresh:normalized,key=`${config.id}:${group}`,cursor=Number(cursorStore.get?.(key)??cursorStore.dialogueCursor??0),affinity=config.likedInteractions?.includes(context.action)?1:config.dislikedInteractions?.includes(context.action)?2:0,offset=TIME_ORDER.indexOf(time)+RELATION_ORDER.indexOf(relation)+affinity,chosen=pool[(cursor+Math.max(0,offset))%pool.length];if(cursorStore.set)cursorStore.set(key,cursor+1);else cursorStore.dialogueCursor=cursor+1;return{id:`${config.id}-${chosen.id}`,text:chosen.text,time,relationship:relation,event:context.event||context.behavior||'',state:context.state||context.mood||'idle'} }
function behaviorEntries(config){return Object.entries(config.behaviorWeights||{}).filter(([,weight])=>weight>0)}
function chooseBehavior(id,context={}){const config=get(id),key=config.id,recent=(recentBehaviors.get(key)||[]).slice(-2);let pool=behaviorEntries(config).filter(([name])=>!recent.includes(name));if(!pool.length)pool=behaviorEntries(config);const active=config.activeHours.includes(context.time||chinaTime()),total=pool.reduce((sum,[,weight])=>sum+weight*(active?1:.72),0);let cursor=Math.random()*total,choice=pool.find(([,weight])=>(cursor-=weight*(active?1:.72))<=0)?.[0]||pool[0]?.[0]||'wait';recentBehaviors.set(key,[...recent,choice].slice(-3));return choice}
function activityScore(id,time=chinaTime()){const config=get(id);return(config.activeHours.includes(time)?1:.48)*(1+(100-(config.traits.reserve||50))/180)}
function animationFor(id,behavior){return get(id).behaviorAnimations?.[behavior]||behavior}
function emptyMemory(){return{lastSeen:0,lastInteraction:0,lastFeed:0,recentDialogueIds:[],recentBehaviors:[],dialogueCursor:0,approachCount:0,totalActiveBehaviors:0}}
class CharacterPersonality{
  constructor(config){this.config=config;this.traits=config.traits;this.memoryKey=config.memoryKey||'';this.memory=this.readMemory();this.previousSeen=this.memory.lastSeen;this.awayMs=this.previousSeen?Math.max(0,Date.now()-this.previousSeen):0;this.sessionStarted=Date.now();this.sessionApproachCount=0;this.markSeen();this.onVisibility=()=>{if(document.visibilityState==='hidden')this.markSeen()};document.addEventListener('visibilitychange',this.onVisibility);window.addEventListener('pagehide',this.onVisibility)}
  readMemory(){if(!this.memoryKey)return emptyMemory();try{return{...emptyMemory(),...JSON.parse(localStorage.getItem(this.memoryKey)||'{}')}}catch(_){return emptyMemory()}}
  save(){if(!this.memoryKey)return;try{localStorage.setItem(this.memoryKey,JSON.stringify(this.memory))}catch(_){}}
  markSeen(){this.memory.lastSeen=Date.now();this.save()}
  recordInteraction(action){this.memory.lastInteraction=Date.now();if(action==='feed')this.memory.lastFeed=this.memory.lastInteraction;this.markSeen()}
  time(){return chinaTime()}
  chooseBehavior(context={}){const age=Date.now()-this.sessionStarted;if(this.config.forceApproachAfter&&age>this.config.forceApproachAfter&&!this.sessionApproachCount&&this.config.behaviorWeights.approach){this.recordBehavior('approach');return'approach'}const recent=this.memory.recentBehaviors.slice(-Math.min(5,Math.max(0,behaviorEntries(this.config).length-1)));let pool=behaviorEntries(this.config).filter(([name])=>!recent.includes(name));if(!pool.length)pool=behaviorEntries(this.config);let cursor=Math.random()*pool.reduce((sum,[,weight])=>sum+weight,0),choice=pool.find(([,weight])=>(cursor-=weight)<=0)?.[0]||pool[0][0];this.recordBehavior(choice);return choice}
  recordBehavior(name){this.memory.recentBehaviors=[...this.memory.recentBehaviors,name].slice(-5);this.memory.totalActiveBehaviors++;if(name==='approach'){this.memory.approachCount++;this.sessionApproachCount++}this.markSeen()}
  dialogue(context={}){const line=chooseLine(this.config,context,this.memory.recentDialogueIds,this.memory);this.memory.recentDialogueIds=[...this.memory.recentDialogueIds,line.id].slice(-8);this.markSeen();return{...line,traits:this.traits}}
  openingEvent(force=false){if(this.awayMs>=18*60*60*1000&&this.config.returnDialogue)return{id:'missed-you',behavior:'approach',text:this.config.returnDialogue,awayMs:this.awayMs};const events=this.config.openingEvents||[];if(!events.length||(!force&&Math.random()>(this.config.openingChance||0)))return null;const event=events[(new Date().getDate()+this.memory.dialogueCursor)%events.length];this.memory.dialogueCursor++;this.markSeen();return{...event,awayMs:this.awayMs}}
  debug(){return{id:this.config.id,traits:{...this.traits},activeHours:[...this.config.activeHours],time:this.time(),awayMs:this.awayMs,sessionAge:Date.now()-this.sessionStarted,sessionApproachCount:this.sessionApproachCount,memory:{...this.memory}}}
  destroy(){document.removeEventListener('visibilitychange',this.onVisibility);window.removeEventListener('pagehide',this.onVisibility)}
}
function dialogue(id,context,recent){return chooseLine(get(id),context,recent)}
function count(id){return Object.values(get(id)?.dialogue||{}).reduce((sum,lines)=>sum+lines.length,0)}
function total(){return[...registry.keys()].reduce((sum,id)=>sum+count(id),0)}
window.FluffyPersonalities={register,get,all:()=>[...registry.values()],dialogue,count,total,chooseBehavior,activityScore,animationFor,chinaTime,relationship,CharacterPersonality};
})();
